[tool:pytest]
# Test discovery
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Output options
addopts = 
    --verbose
    --tb=short
    --strict-markers
    --disable-warnings
    --color=yes

# Coverage options
# (These are overridden by command line args in CI)
markers = 
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests

# Minimum coverage thresholds
# These can be enforced with --cov-fail-under in CI
filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning